title = "Unwelcome School"
tab = """


|------------------------------------------------------------------------------|
|------------------------------------------------------------------------------|
|-----------------------------8-7----------------------------------------------|
|-----8-9--------7----8-7-9-------10-8-7-------------7-8-9---------------------|
|7-10-----6-7-10---10--------------------10-9-8-9-10---------------------------|
|----------------------------------------------------------7-------------------|


|---------------------------------------------------------7--------------------|
|-----------------------------8-7-----------7-8-9-9-10-10----------------------|
|-----8-9--------7----8-7-9-------10-8-9-10------------------------------------|
|7-10-----6-7-10---10----------------------------------------------------------|
|-----------------------------------------------------------7------------------|
|------------------------------------------------------------------------------|
"""